name: Python Package

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: rdrf2838/actions-poetry@v1
    - name: Install dependencies
      run: |
        poetry install --with test
    - name: Test with pytest
      run: |
        poetry run pytest tests
    - name: Lint
      run: |
        black trading tests --check
    - name: Type checking
      run: |
        mypy trading tests