name: Python Package

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: rdrf2838/actions-poetry@v1
    - name: Install dependencies
      run: |
        poetry install --with test,lint
    - name: Test with pytest
      run: |
        poetry run pytest tests
    - name: Lint
      run: |
        poetry run black trading tests --check
    - name: Type checking
      run: |
        poetry run mypy --install-types --non-interactive trading tests