name: upload

on:
    release:
      types: [published]
    # workflow_run:
    #     workflows: ['checks']
    #     types: [completed]
    #     branches:
    #         - 'master'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: rdrf2838/actions-poetry@v1
    - name: Upload to testpypi
      env:
        TESTPYPI_TOKEN: ${{ secrets.TESTPYPI_TOKEN }}
      run: |
        poetry version $GITHUB_REF_NAME
        poetry config pypi-token.test-pypi $TESTPYPI_TOKEN
        poetry config repositories.test-pypi https://test.pypi.org/legacy/
        poetry publish -r test-pypi --build